title: Bob Umerkulov
email: b.umerkulov@gmail.com
baseurl: "/"
url: "https://umerkulovb.com/"
google_analytics: UA-82816934-1

# Build settings
markdown: kramdown

author:
  photo: /images/me.jpg
  github: https://github.com/umerkulovb

social:
  mail: "mailto:b.umerkulov@gmail.com"
  github: "https://github.com/umerkulovb"
  twitter: "https://twitter.com/umerkulovb"
  linkedin: "https://linkedin.com/in/umerkulovb"
