title: Bob Umerkulov
email: b.umerkulov@gmail.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://umerkulovb.github.io" # the base hostname & protocol for your site
google_analytics: UA-82816934-1

# Build settings
markdown: kramdown

author:
  photo: /images/me.jpg
  email: b.umerkulov@gmail.com
  github: https://github.com/umerkulovb
