title: Bobur Umerkulov
email: b.umerkulov@gmail.com
baseurl: "/"
url: "https://umerkulovb.com/"
google_analytics: UA-82816934-1
description: Bobur Umerkulov, staff software engineer - team lead

# Build settings
markdown: kramdown

author:
  photo: /images/me.jpeg
  github: https://github.com/umerkulovb

social:
  mail: "mailto:b.umerkulov@gmail.com"
  file-pdf: "/files/Bobur_Umerkulov_CV.pdf"
  github: "https://github.com/umerkulovb"
  linkedin: "https://linkedin.com/in/umerkulovb"
